providers:
  docker:
    # do not expose containers that do not have a traefik.enable=true label
    exposedByDefault: false

entryPoints:
  # entry point for services - port numbers are not important because these (container) ports
  # are mapped anyway to host ports defined in .env file (JENKINS_PORT, ...): see docker-compose.yml
  https-jenkins:
    address: ":8083"

api:
  dashboard: true
  insecure: true