version: '3.5'

networks:
  network_jenkins:
    name: network_jenkins

services:

  jenkins:
    build:
      context: ./jenkins
    image: jenkins-test
    container_name: jenkins-test
    user: ":${GID_JENKINS_DOCKER}"
    # network_mode: host
    networks:
      - network_jenkins
    ports:
      # - "${JENKINS_PORT}:${JENKINS_PORT}"
      - "${JENKINS_SLAVE_AGENT_PORT}:${JENKINS_SLAVE_AGENT_PORT}"
    expose:
      # exposing port 80 to other docker-compose services (i.e. to traefik) - but not to outside world
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JENKINS_DATA_DIR}:/var/jenkins_home
    environment:
      - JENKINS_SLAVE_AGENT_PORT=${JENKINS_SLAVE_AGENT_PORT}
      - JENKINS_OPTS="--httpPort=80"  # --prefix=/jenkins"
      - JAVA_OPTS="-Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Paris -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=300"
    labels:
      # expose service in traefik
      - "traefik.enable=true"
      # rerouting all https requests received by traefik through Jenkins
      # entry point to (port 80 of) jenkins service
      - "traefik.http.routers.jenkins.entrypoints=https-jenkins"
      - "traefik.http.routers.jenkins.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.jenkins.tls=true"
      - "traefik.http.services.jenkins.loadbalancer.server.port=80"
#      - "traefik.http.routers.jenkins.middlewares=add-jenkins"
#      - "traefik.http.middlewares.add-jenkins.addprefix.prefix=/jenkins/"
      - "traefik.docker.network=network_jenkins"
    restart: unless-stopped

  reverse-proxy-for-jenkins:
    build:
      context: ./reverse-proxy
    image: traefik-for-jenkins
    container_name: traefik-for-jenkins
    networks:
      - network_jenkins
    ports:
      # let traefik listen to Jenkins port (and redirect all request to Jenkins)
      - "${JENKINS_PORT}:8083"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"  # Web UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
